# Generated by Django 4.2.3 on 2023-07-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_fecharegistro_user_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='perfil',
        ),
    ]
