# Generated by Django 4.2.3 on 2023-07-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_user_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
